# Generated by Django 6.0.3 on 2026-09-19 00:58

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objectsc', django.db.models.manager.Manager()),
            ],
        ),
    ]
