# Generated by Django 6.0.3 on 2026-09-21 00:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_article_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects_author', django.db.models.manager.Manager()),
            ],
        ),
    ]
