# Generated by Django 6.0.3 on 2026-09-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Book',
        ),
    ]
